### ISSUE TITLE
java.util.NoSuchElementException: next on empty iterator

### ISSUE THREAD

**Issue by garmonbozzzia** [EncryFoundation/EncryCore#48]
[encry-akka.actor.default-dispatcher-23] >> [WARN ] e.v.history.storage.HistoryStorage >> 18:14:32.054 Failed to parse block from db: 
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:38)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:36)
	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:60)
	at scala.collection.IterableLike.head(IterableLike.scala:106)
	at scala.collection.IterableLike.head$(IterableLike.scala:105)
	at scala.collection.mutable.ArrayOps$ofByte.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:206)
	at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:125)
	at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:125)
	at scala.collection.mutable.ArrayOps$ofByte.head(ArrayOps.scala:206)
	at encry.modifiers.history.HistoryModifierSerializer$.$anonfun$parseBytes$1(HistoryModifierSerializer.scala:24)
	at scala.runtime.java8.JFunction0$mcB$sp.apply(JFunction0$mcB$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at encry.modifiers.history.HistoryModifierSerializer$.parseBytes(HistoryModifierSerializer.scala:24)
	at encry.view.history.storage.HistoryStorage.$anonfun$modifierById$1(HistoryStorage.scala:17)
	at scala.Option.flatMap(Option.scala:171)
	at encry.view.history.storage.HistoryStorage.modifierById(HistoryStorage.scala:16)
	at encry.view.history.EncryHistoryReader.modifierById(EncryHistoryReader.scala:159)
	at encry.view.history.EncryHistoryReader.modifierById$(EncryHistoryReader.scala:158)
	at encry.view.history.EncryHistory$$anon$2.modifierById(EncryHistory.scala:197)
	at scorex.core.consensus.HistoryReader.contains(HistoryReader.scala:29)
	at scorex.core.consensus.HistoryReader.contains$(HistoryReader.scala:29)
	at encry.view.history.EncryHistory$$anon$2.contains(EncryHistory.scala:197)
	at encry.view.history.processors.DownloadProcessor.$anonfun$modifiersToDownload$4(DownloadProcessor.scala:52)
	at encry.view.history.processors.DownloadProcessor.$anonfun$modifiersToDownload$4$adapted(DownloadProcessor.scala:52)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at encry.view.history.processors.DownloadProcessor.continuation$1(DownloadProcessor.scala:52)
	at encry.view.history.processors.DownloadProcessor.modifiersToDownload(DownloadProcessor.scala:61)
	at encry.view.history.processors.DownloadProcessor.modifiersToDownload$(DownloadProcessor.scala:43)
	at encry.view.history.EncryHistory$$anon$2.modifiersToDownload(EncryHistory.scala:197)
	at encry.network.EncryNodeViewSynchronizer$$anonfun$onCheckModifiersToDownload$1.$anonfun$applyOrElse$2(EncryNodeViewSynchronizer.scala:67)
	at encry.network.EncryNodeViewSynchronizer$$anonfun$onCheckModifiersToDownload$1.$anonfun$applyOrElse$2$adapted(EncryNodeViewSynchronizer.scala:65)
	at scala.Option.foreach(Option.scala:257)
	at encry.network.EncryNodeViewSynchronizer$$anonfun$onCheckModifiersToDownload$1.applyOrElse(EncryNodeViewSynchronizer.scala:65)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at encry.network.NodeViewSynchronizer.aroundReceive(NodeViewSynchronizer.scala:29)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by garmonbozzzia** [comment]
[encry-akka.actor.default-dispatcher-13] >> [INFO ] e.network.EncryNodeViewSynchronizer >> 18:14:56.045 Got modifiers of type 102 from remote connected peer: ConnectedPeer(172.16.10.55/172.16.10.55:9001)
[encry-akka.actor.default-dispatcher-24] >> [INFO ] encry.view.EncryNodeViewHolder >> 18:14:56.046 Persistent modifier EEK9mGt6diBjTdZTfcfczo7vTiFypcxZj35gktP45AzB applied successfully
[encry-akka.actor.default-dispatcher-24] >> [DEBUG] encry.view.EncryNodeViewHolder >> 18:14:56.046 Cache after(0): 
[encry-akka.actor.default-dispatcher-24] >> [INFO ] encry.view.EncryNodeViewHolder >> 18:14:56.046 Got locally generated modifier DN5Gp1EkkgU4DdBzheMHN7KGpv1n75qsu55K336szd8t of type 104
[encry-akka.actor.default-dispatcher-24] >> [INFO ] encry.view.EncryNodeViewHolder >> 18:14:56.046 Apply modifier DN5Gp1EkkgU4DdBzheMHN7KGpv1n75qsu55K336szd8t of type 104 to nodeViewHolder
[encry-akka.actor.default-dispatcher-24] >> [DEBUG] e.view.history.EncryHistory$$anon$2 >> 18:14:56.046 Trying to append modifier DN5Gp1EkkgU4DdBzheMHN7KGpv1n75qsu55K336szd8t of type 104 to history
[encry-akka.actor.default-dispatcher-13] >> [WARN ] e.v.history.storage.HistoryStorage >> 18:14:56.048 Failed to parse block from db: 
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:38)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:36)
	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:60)
